mfm.root.path=${MFM_ROOT_PATH:${user.home}/base/volumedogane/mfm-files}
mfm.security.dev-user-name=Local developer
mfm.security.dev-user-email=developer@localhost

server.servlet.session.cookie.secure=false
