mfm.root.path=${MFM_ROOT_PATH}
mfm.security.allowed-identities=${MFM_ALLOWED_IDENTITIES:}
mfm.security.allowed-emails=${MFM_ALLOWED_EMAILS:}

server.address=${MFM_SERVER_ADDRESS:127.0.0.1}
server.port=${MFM_SERVER_PORT:8080}

spring.security.oauth2.client.registration.mfm.provider=mfm
spring.security.oauth2.client.registration.mfm.client-id=${OIDC_CLIENT_ID}
spring.security.oauth2.client.registration.mfm.client-secret=${OIDC_CLIENT_SECRET}
spring.security.oauth2.client.registration.mfm.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.mfm.scope=openid,profile,email
spring.security.oauth2.client.registration.mfm.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.mfm.issuer-uri=${OIDC_ISSUER_URI}

server.servlet.session.cookie.secure=true
